# Generated by Django 4.2.10 on 2024-02-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='is_first_hack',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='Yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(default='Undeclared', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=-1111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.CharField(default=-1111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='short_answer1',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='short_answer2',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='teammate_1',
            field=models.CharField(default='teammate1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='teammate_2',
            field=models.CharField(default='teammate2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='teammate_3',
            field=models.CharField(default='teammate3', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.CharField(default='year', max_length=4),
            preserve_default=False,
        ),
    ]
