# Generated by Django 5.0.1 on 2024-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennapps', '0003_alter_application_teammate_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='short_answer1',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='short_answer2',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='teammate_1',
            new_name='team_member_1',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='teammate_2',
            new_name='team_member_2',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='teammate_3',
            new_name='team_member_3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_first_hack',
        ),
        migrations.AddField(
            model_name='application',
            name='first_hackathon',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='N/A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('WLST', 'Waitlisted'), ('PROC', 'Processing')], default='PROC', max_length=4),
        ),
    ]
